# Generated by Django 6.0.2 on 2026-04-24 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darslik_platforma_bbc', '0002_category_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Matn yoki tushuntirish')),
                ('video_url', models.URLField(blank=True, help_text='YouTube yoki Vimeo link', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Darslar tartibi')),
                ('is_free', models.BooleanField(default=False, help_text='Bepul preview uchun')),
                ('duration_minutes', models.PositiveIntegerField(default=0, help_text='Dars davomiyligi (minut)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='darslik_platforma_bbc.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
