# Generated by Django 6.0.2 on 2026-04-26 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darslik_platforma_bbc', '0008_question_answer_quiz_question_quiz_quizattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('enrollment', 'Yangi yozilish'), ('review', 'Yangi sharh'), ('certificate', 'Sertifikat tayyor'), ('new_lesson', 'Yangi dars'), ('new_course', 'Yangi kurs'), ('quiz_passed', 'Test muvaffaqiyatli'), ('quiz_failed', 'Test muvaffaqiyatsiz'), ('course_completed', 'Kurs tugatildi'), ('system', 'Tizim xabari')], default='system', max_length=30, verbose_name='Tur')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('link', models.CharField(blank=True, default='', max_length=500)),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilgan")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='darslik_platforma_bbc.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': 'Bildirishnomalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
